### ISSUE TITLE
Autosave not working! (Save chat option doesn't works) 

### ISSUE THREAD

**Issue by Lucky-069** [rodit/SnapMod#129] opened 2022-05-16 18:05 UTC
The autosave messages doesn't seems to be working! Can anyone else confirm. Everything else works for me but not autosave messages!

**Comment by Magna-Graecia** [comment] 2022-05-16 22:21
It's working for me as well for what it's worth, so it's likely a local issue to you.

**Comment by Lucky-069** [comment] 2022-05-17 05:43
> Try turning it on front the snapmod app. It works perfect for me

Wdym by front the snapmod app. I had the option enabled and even force stop app and restarted it. Tried toggling but all the chats seem to be unsaved as snap would regularly do

**Comment by Lucky-069** [comment] 2022-05-17 08:53
Also is the autosaving done locally or over the server? Like how we manually save chats and other stuff on snapchat. I mean the autosave doesn't works in form of cache right?

**Comment by rodit** [comment] 2022-05-17 11:36
It saves in the exact same way as if you did it manually by tapping the message (so no local store of saved messages is kept, and yes the server knows about it). I'm not sure why it wouldn't work for you, please could you give some details about your android version, xposed installation and logs too.

**Comment by Lucky-069** [comment] 2022-05-17 15:24
Oh yes I'll send the logs right away! Just a moment!

**Comment by Lucky-069** [comment] 2022-05-17 16:03
(Logs here)[https://anonfiles.com/n6bev0h2y8/LSPosed_2022-05-17T21_17_01.019_zip]

**Comment by Lucky-069** [comment] 2022-05-17 16:03
> I'm on andoird 11, redmi Note 8 pro with magisk v23 and lsposed latest version available. Everything on snapmod works for me but autosave so I was wondering where the issue is. I even downloaded the binding.json and replaced it manually in /data/data/xyz.... To where it originally is located. Rebooted device. Tried toggling the settings but won't work.

Here's the logs :https://anonfiles.com/n6bev0h2y8/LSPosed_2022-05-17T21_17_01.019_zip

**Comment by rodit** [comment] 2022-05-17 16:59
Unfortunately, I can't access the logs (I get bad gateway, even when using a proxy/vpn). You can attach them directly to your reply on github (at the bottom of the text editor).

**Comment by Lucky-069** [comment] 2022-05-17 20:00
[Uploading LSPosed_2022-05-17T21_17_01.019.zip…]()

**Comment by rodit** [comment] 2022-05-17 20:08
I'm not sure what happened but that link is also not downloadable

**Comment by Lucky-069** [comment] 2022-05-17 20:34
Ugh that's annoying. Can I just copy paste the text logs?

**Comment by Lucky-069** [comment] 2022-05-17 20:38
@rodit
[LSPosed_2022-05-18T02_04_19.924.zip](https://github.com/rodit/SnapMod/files/8711404/LSPosed_2022-05-18T02_04_19.924.zip)

**Comment by rodit** [comment] 2022-05-17 21:03
Thanks - do you have everything checked in the 'Log Level' option? Also I'd recommend disabling log network requests before posting logs - they might contain auth tokens etc.

And yes, copying and pasting the module logs is fine.

**Comment by Lucky-069** [comment] 2022-05-17 21:39
Oh okay I'll rather do that. I'll copy paste the logs!

**Comment by Lucky-069** [comment] 2022-05-17 21:55
----part 2 start----
[ 2022-05-18T03:15:21.432    10074: 20439: 20439 I/LSPosed-Bridge  ] Loading module com.ceco.r.gravitybox from /data/app/~~gQchr1rOTUOaJEANHD_UVw==/com.ceco.r.gravitybox-GHxb7c4a1LJ7aL2VOaXRhw==/base.apk
[ 2022-05-18T03:15:21.477    10074: 20439: 20439 I/LSPosed-Bridge  ]   Loading class com.ceco.r.gravitybox.GravityBox
[ 2022-05-18T03:15:40.246    11443: 20838: 20838 I/LSPosed-Bridge  ] Loading module com.kieronquinn.app.darq from /data/app/~~x5gQazLzLAW7WzSXExSvYA==/com.kieronquinn.app.darq-YoxCyUnPfrlOIayBfP_NBg==/base.apk
[ 2022-05-18T03:15:40.623    11443: 20838: 20838 I/LSPosed-Bridge  ]   Loading class com.kieronquinn.app.darq.Xposed
[ 2022-05-18T03:15:40.632    11443: 20838: 20838 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~sruCDqpvHAg_sLTs8okuCw==/xyz.rodit.snapmod-Zx-Hj6gxV3Y9KyGezJjMpw==/base.apk
[ 2022-05-18T03:15:40.887    11443: 20838: 20838 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-05-18T03:15:42.355    11443: 20838: 20838 I/LSPosed-Bridge  ] Context hook com.snap.mushroom.app.MushroomApplication@7808585, [android.app.ContextImpl@5f52fef]
[ 2022-05-18T03:15:42.480    11440: 20933: 20933 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~sruCDqpvHAg_sLTs8okuCw==/xyz.rodit.snapmod-Zx-Hj6gxV3Y9KyGezJjMpw==/base.apk
[ 2022-05-18T03:15:42.792    11443: 20838: 20838 I/LSPosed-Bridge  ] Loaded cached mappings for build 84608.
[ 2022-05-18T03:15:42.846    11440: 20933: 20933 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-05-18T03:15:43.450    11525: 20969: 20969 I/LSPosed-Bridge  ] Loading module icu.nullptr.twifucker from /data/app/~~WCqUALQ3u98wWR-Rvd7eFQ==/icu.nullptr.twifucker-yBEEvyYzRQVmjSNqqkhsVA==/base.apk
[ 2022-05-18T03:15:43.457    11525: 20969: 20969 I/LSPosed-Bridge  ]   Loading class icu.nullptr.twifucker.hook.HookEntry
[ 2022-05-18T03:16:37.459    10154: 22087: 22087 I/LSPosed-Bridge  ] Loading module com.ceco.r.gravitybox from /data/app/~~gQchr1rOTUOaJEANHD_UVw==/com.ceco.r.gravitybox-GHxb7c4a1LJ7aL2VOaXRhw==/base.apk
[ 2022-05-18T03:16:37.491    10154: 22087: 22087 I/LSPosed-Bridge  ]   Loading class com.ceco.r.gravitybox.GravityBox
[ 2022-05-18T03:16:37.616    10154: 22087: 22087 I/LSPosed-Bridge  ] Loading module com.imadev.nsfw from /data/app/~~hFHlwCHS3JUwwvOqFuemcA==/com.imadev.nsfw-g8wt44kdS4XUUqQbXf_1AA==/base.apk
[ 2022-05-18T03:16:37.617    10154: 22087: 22087 I/LSPosed-Bridge  ]   Loading class com.imadev.nsfw.Hook
[ 2022-05-18T03:18:14.178    11443: 22739: 22739 I/LSPosed-Bridge  ] Loading module com.kieronquinn.app.darq from /data/app/~~x5gQazLzLAW7WzSXExSvYA==/com.kieronquinn.app.darq-YoxCyUnPfrlOIayBfP_NBg==/base.apk
[ 2022-05-18T03:18:14.403    11443: 22739: 22739 I/LSPosed-Bridge  ]   Loading class com.kieronquinn.app.darq.Xposed
[ 2022-05-18T03:18:14.408    11443: 22739: 22739 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~sruCDqpvHAg_sLTs8okuCw==/xyz.rodit.snapmod-Zx-Hj6gxV3Y9KyGezJjMpw==/base.apk
[ 2022-05-18T03:18:14.569    11443: 22739: 22739 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-05-18T03:18:16.290    11443: 22739: 22739 I/LSPosed-Bridge  ] Context hook com.snap.mushroom.app.MushroomApplication@7808585, [android.app.ContextImpl@eeaf4ce]
[ 2022-05-18T03:18:16.722    11443: 22739: 22739 I/LSPosed-Bridge  ] Loaded cached mappings for build 84608.
[ 2022-05-18T03:18:23.761    10161: 22790: 22790 I/LSPosed-Bridge  ] Loading module nfg.multi_crack.android from /data/app/~~9KlhUFCap_bD3otjd2whug==/nfg.multi_crack.android-I1XLdoC_QvTQw9mNjuMxEA==/base.apk
[ 2022-05-18T03:18:23.793    10395: 22802: 22802 I/LSPosed-Bridge  ] Loading module nfg.multi_crack.android from /data/app/~~9KlhUFCap_bD3otjd2whug==/nfg.multi_crack.android-I1XLdoC_QvTQw9mNjuMxEA==/base.apk
[ 2022-05-18T03:18:23.864    10161: 22790: 22790 I/LSPosed-Bridge  ]   Loading class nfg.multi_crack.android.Xposed.XposedEntry
[ 2022-05-18T03:18:23.882    10395: 22802: 22802 I/LSPosed-Bridge  ]   Loading class nfg.multi_crack.android.Xposed.XposedEntry
[ 2022-05-18T03:18:47.379    10074: 23114: 23114 I/LSPosed-Bridge  ] Loading module com.ceco.r.gravitybox from /data/app/~~gQchr1rOTUOaJEANHD_UVw==/com.ceco.r.gravitybox-GHxb7c4a1LJ7aL2VOaXRhw==/base.apk
[ 2022-05-18T03:18:47.405    10074: 23114: 23114 I/LSPosed-Bridge  ]   Loading class com.ceco.r.gravitybox.GravityBox
[ 2022-05-18T03:20:05.756    10159: 23604: 23604 I/LSPosed-Bridge  ] Loading module ru.sxbuIDfx.pFSOyagrF from /data/app/~~8KzeDa2Hoklhbj3OtCCocQ==/ru.sxbuIDfx.pFSOyagrF-pETo4b6L2iEQncf1eSscuQ==/base.apk
[ 2022-05-18T03:20:05.824    10159: 23604: 23604 I/LSPosed-Bridge  ]   Loading class com.xposed.XSupport
[ 2022-05-18T03:20:07.223    10159: 23691: 23691 I/LSPosed-Bridge  ] Loading module ru.sxbuIDfx.pFSOyagrF from /data/app/~~8KzeDa2Hoklhbj3OtCCocQ==/ru.sxbuIDfx.pFSOyagrF-pETo4b6L2iEQncf1eSscuQ==/base.apk
[ 2022-05-18T03:20:07.270    10159: 23691: 23691 I/LSPosed-Bridge  ]   Loading class com.xposed.XSupport
[ 2022-05-18T03:20:34.765    11440: 24108: 24108 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~9Arn7o_oFSCd4VukFFgX9A==/xyz.rodit.snapmod-KprWHghxeFb9rcd4shnwjA==/base.apk
[ 2022-05-18T03:20:34.985    11440: 24108: 24108 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-05-18T03:21:00.221    11525: 24525: 24525 I/LSPosed-Bridge  ] Loading module icu.nullptr.twifucker from /data/app/~~WCqUALQ3u98wWR-Rvd7eFQ==/icu.nullptr.twifucker-yBEEvyYzRQVmjSNqqkhsVA==/base.apk
[ 2022-05-18T03:21:00.227    11525: 24525: 24525 I/LSPosed-Bridge  ]   Loading class icu.nullptr.twifucker.hook.HookEntry
[ 2022-05-18T03:21:09.034    11443: 24667: 24667 I/LSPosed-Bridge  ] Loading module com.kieronquinn.app.darq from /data/app/~~x5gQazLzLAW7WzSXExSvYA==/com.kieronquinn.app.darq-YoxCyUnPfrlOIayBfP_NBg==/base.apk
[ 2022-05-18T03:21:09.311    11443: 24667: 24667 I/LSPosed-Bridge  ]   Loading class com.kieronquinn.app.darq.Xposed
[ 2022-05-18T03:21:09.317    11443: 24667: 24667 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~9Arn7o_oFSCd4VukFFgX9A==/xyz.rodit.snapmod-KprWHghxeFb9rcd4shnwjA==/base.apk
[ 2022-05-18T03:21:09.512    11443: 24667: 24667 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-05-18T03:21:10.692    11443: 24667: 24667 I/LSPosed-Bridge  ] Context hook com.snap.mushroom.app.MushroomApplication@7808585, [android.app.ContextImpl@eeaf4ce]
[ 2022-05-18T03:21:10.921    11443: 24667: 24667 I/LSPosed-Bridge  ] Loaded cached mappings for build 84608.

Logd maybe crashed (err=Socket operation on non-socket), retrying in 1s...
[ 2022-05-18T03:21:39.630    11443: 25194: 25194 I/LSPosed-Bridge  ] Loading module com.kieronquinn.app.darq from /data/app/~~x5gQazLzLAW7WzSXExSvYA==/com.kieronquinn.app.darq-YoxCyUnPfrlOIayBfP_NBg==/base.apk
[ 2022-05-18T03:21:39.881    11443: 25194: 25194 I/LSPosed-Bridge  ]   Loading class com.kieronquinn.app.darq.Xposed
[ 2022-05-18T03:21:39.887    11443: 25194: 25194 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~9Arn7o_oFSCd4VukFFgX9A==/xyz.rodit.snapmod-KprWHghxeFb9rcd4shnwjA==/base.apk
[ 2022-05-18T03:21:40.098    11443: 25194: 25194 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-05-18T03:21:41.831    11443: 25194: 25194 I/LSPosed-Bridge  ] Context hook com.snap.mushroom.app.MushroomApplication@7808585, [android.app.ContextImpl@5f52fef]
[ 2022-05-18T03:21:42.305    11443: 25194: 25194 I/LSPosed-Bridge  ] Loaded cached mappings for build 84608.
[ 2022-05-18T03:22:16.509    11443: 25511: 25511 I/LSPosed-Bridge  ] Loading module com.kieronquinn.app.darq from /data/app/~~x5gQazLzLAW7WzSXExSvYA==/com.kieronquinn.app.darq-YoxCyUnPfrlOIayBfP_NBg==/base.apk
[ 2022-05-18T03:22:16.769    11443: 25511: 25511 I/LSPosed-Bridge  ]   Loading class com.kieronquinn.app.darq.Xposed
[ 2022-05-18T03:22:16.777    11443: 25511: 25511 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~9Arn7o_oFSCd4VukFFgX9A==/xyz.rodit.snapmod-KprWHghxeFb9rcd4shnwjA==/base.apk
[ 2022-05-18T03:22:16.985    11443: 25511: 25511 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-05-18T03:22:18.654    11443: 25511: 25511 I/LSPosed-Bridge  ] Context hook com.snap.mushroom.app.MushroomApplication@7808585, [android.app.ContextImpl@5f52fef]
[ 2022-05-18T03:22:18.730    11440: 25543: 25543 I/LSPosed-Bridge  ] Loading module xyz.rodit.snapmod from /data/app/~~9Arn7o_oFSCd4VukFFgX9A==/xyz.rodit.snapmod-KprWHghxeFb9rcd4shnwjA==/base.apk
[ 2022-05-18T03:22:18.928    11440: 25543: 25543 I/LSPosed-Bridge  ]   Loading class xyz.rodit.snapmod.SnapHooks
[ 2022-05-18T03:22:19.098    11443: 25511: 25511 I/LSPosed-Bridge  ] Loaded cached mappings for build 84608.

**Comment by Lucky-069** [comment] 2022-05-17 21:55
Sorry for annoying you so much. But there's the logs after turning off network logs!

**Comment by rodit** [comment] 2022-05-18 10:04
There's no errors in the logs - and don't worry about 'annoying' me haha.

For something useful to appear in the logs you must enable the auto save option then perform an action that should trigger autosaving (i.e. send it receive a message and view the message).

**Comment by Lucky-069** [comment] 2022-05-18 10:56
Oh i did try that. I tried it I have turned on the feature  also turned on autosave within the chat but it disappears as soon as I view the message.

**Comment by rodit** [comment] 2022-05-18 12:32
What version of snapchat/snapmod are you using. I can't think of any reason why it wouldn't work just for you haha

**Comment by Lucky-069** [comment] 2022-05-18 15:06
I Uninstaller both the apps. Cleared the saved files in data/data and reinstalled snapchat and snapmod. Everything seems to work except autosave. Is there anything as such where in autosave won't work if the person has set the chat to delete immediately after viewing because most of my chats are the same. Well it shouldn't be the case anyways. Since you already said it is as same as manual saving!

**Comment by Lucky-069** [comment] 2022-05-18 15:12
Okay I think I found out why the autosave won't work. Even when I tap save in chat manually it won't save the chat for some reason. Idk that's odd even after I installed it again. This shouldn't be happening. I'm not sure why it's occurring. I'll just recheck but ig that must be the issue.

**Comment by Lucky-069** [comment] 2022-05-18 15:17
I turned off the snapmod for a minute and it seems when the mod is off I get the option to save the chat and it works fine. I believe there's something within the settings that's causing the issue. Since I can't even get to save the chat in the mod manually. It only makes sense autosave won't work.. Should I send ss of the toggles I have on?

**Comment by Lucky-069** [comment] 2022-05-18 15:26
![Screenshot_20220518-205024](https://user-images.githubusercontent.com/78787509/169079569-ed317ef7-b81d-48ef-a1b0-9a0808d09e87.png)
![Screenshot_20220518-205038](https://user-images.githubusercontent.com/78787509/169079624-75ffa8dd-492e-4c79-8ec4-a59c084dd995.png)
![Screenshot_20220518-205141](https://user-images.githubusercontent.com/78787509/169079725-6deae645-a49b-46b0-b46a-186767715cde.png)
![Screenshot_20220518-205130](https://user-images.githubusercontent.com/78787509/169079848-4b3a4a58-35b6-4a70-9ed4-e4e50d44072f.png)
![Screenshot_20220518-205149](https://user-images.githubusercontent.com/78787509/169079987-ba9d1ac5-f655-485d-84cc-82656ae17bf6.png)
![Screenshot_20220518-205159](https://user-images.githubusercontent.com/78787509/169080083-c20dbf19-6959-492c-9fb4-562935ea4030.png)
![Screenshot_20220518-205213](https://user-images.githubusercontent.com/78787509/169080208-fd30f445-f72a-4f55-99eb-52e54b8a76e7.png)

Attaching below the screenshot of the current settings I have enabled within the app. Kindly check and let me know what could cause the issue. Meanwhile I'm doing the so by toggling everything in settings. (Please note: there's something enabled on the mod that is not allowing me to save chats on snapchat.) we just have to find that and turn it off.. The autosave would work then! Also rodit my sincere apologies for this!

**Comment by Lucky-069** [comment] 2022-05-18 16:12
Could anybody let me know what settings they have if autosave works for them!

**Comment by jammyjay** [comment] 2022-05-18 16:20
Which version of Snapchat are you using. There was a note when installing that autosave messages would only work with at least 11.78.1.39 and higher. If you haven't updated your Snapchat in the last 2-3 days, this might be the reason.

For me, Snapchat completely skipped 78.1.39 in the playstore, so had to manually download it from apkmirror

**Comment by Lucky-069** [comment] 2022-05-18 16:26
> Which version of Snapchat are you using. There was a note when installing that autosave messages would only work with at least 11.78.1.39 and higher. If you haven't updated your Snapchat in the last 2-3 days, this might be the reason.
> 
> Edit - I just saw your picture, the reason messages aren't saving for you is because you need to update your Snapchat like I thought.

I'm on the latest version available. It's 11.79.0.34
Like I said there's something within the settings which is messing and it isn't allowing me to save chats! Even the manual way

**Comment by jammyjay** [comment] 2022-05-18 16:31
> > Which version of Snapchat are you using. There was a note when installing that autosave messages would only work with at least 11.78.1.39 and higher. If you haven't updated your Snapchat in the last 2-3 days, this might be the reason.
> > Edit - I just saw your picture, the reason messages aren't saving for you is because you need to update your Snapchat like I thought.
> 
> I'm on the latest version available. It's 11.79.0.34 Like I said there's something within the settings which is messing and it isn't allowing me to save chats! Even the manual way

Could have sworn that was 78.0.39 when I looked at it. My mistake.

**Comment by Lucky-069** [comment] 2022-05-18 17:06
Yup its checked. I checked

**Comment by Lucky-069** [comment] 2022-05-18 18:26
@Magna-Graecia @RevealedSoulEven @rodit could you actually check the settings if there's something that blocking the save chat option!

**Comment by Magna-Graecia** [comment] 2022-05-19 03:53
Make sure you disable "Stealth Mode" on the chat that you're testing it on, and also make sure that all of the global Stealth Mode options are disabled in SnapMod settings (it looks like you have "Hide Typing Notifications" on. Disable that.)

Stealth Mode will stop messages from auto-saving, and that's a GOOD thing and how it's supposed to work. When the messages are saved, the recipient can see it the same way as when it's done manually. There's literally no difference between the auto way and the manual way. The auto way is just "tapping" the messages for you. So if you have any stealth options enabled, but the recipient sees you saving messages, then that blows your stealth cover, right? Imagine if you had "Hide Read Receipts" enabled along with "Auto-Save Messages" enabled. When you went to view a chat, the messages would be auto-saved even though as far as the recipient is concerned, you never read the message since they never received a read receipt because you had the hidden option for it enabled. So then how did you save the messages?? BUSTED! So you see my point. The same applies to other stealth aspects like "Hide Bitmoji Presence". You wouldn't want to be auto-saving messages while viewing a chat with your bitmoji hidden. It doesn't make sense, and if the other person was in the chat it would give you away. 

Personally, I don't have any of the global Stealth Mode options enabled. I toggle Stealth Mode on individual chats as needed. But when Stealth Mode is enabled and I view a chat with auto-save messages enabled, the messages won't auto-save, and I like that because it doesn't give me away. Even if I tap on a message while viewing it with Stealth Mode enabled, it will do nothing. Saving is completely disabled while Stealth Mode is active. Like I said, it wouldn't make sense if the recipient sees that I haven't read their messages but yet am saving them in the chat. BOINK! So this is working as intended. Try making sure these options are disabled.

**Comment by Lucky-069** [comment] 2022-05-19 05:09
I turned off all the privacy settings still the issue persists. Also I don't think hide Bitmoji presence or typing would cause any problem. Since when I send the message the user still gets notification right! So I don't think that's the problem. I tries turning off everything in privacy settings and it still is the same. Could someone trying sending ss of their settings or try to replicate the settings I have so we can know where the actual issue is. I have been trying for a few hours but it doesn't seems to work anyways!!

**Comment by Magna-Graecia** [comment] 2022-05-19 05:33
I mirrored your settings but wasn't able to replicate your issue. I can assure you though that currently when I have both Stealth Mode and Auto-Save Messages enabled and view a chat with new messages, they don't get auto-saved. Once I disable Stealth Mode and view the message again, they will get auto-saved, and I like it working like this because I don't want messages auto-saving when the recipient thinks I haven't even read the message yet, or am not in the chat (hide bitmoji presence). I think rodit specifically designed it this way for this reason. So I thought having any of these features enabled might have been your issue.

Did you go into SnapMod settings and make sure that "Chats" is checked under "Auto-Save Message Types"?

**Comment by Lucky-069** [comment] 2022-05-19 07:37
@rodit sorry for tagging you on this. But idk if it's a bug, autosave seems to be working for others, but save in chat option won't work for me even manually. I have tried to turn off every option in privacy settings, yet it exists. I think you might have the best knowledge of what's causing such an issue. I can confirm when I completely turn off the mod in lsposed. It works just fine so it has something to do with the snapmod somehow.

**Comment by Lucky-069** [comment] 2022-05-19 08:27
So I checked disabling every option in mod now, yet somehow the save in chat option won't work for me. It is clickable but it won't save anything. However when I disable the mod from lsposed save chat works fine on stock snapchat. So I'm sure there's something within the app that is causing this issue. I'm on redmi note 8 pro running android 11 with magisk v23 and lsposed latest version available. I doubt it would be device specific tho but for the sake of my satisfaction I shall delete the files in data/data/xyz.... first, restart the phone again uninstalling the mod and again install the mod and restart to be 💯 sure it isn't device specific.

I'll keep updating whatever I notice or can understand

**Comment by Lucky-069** [comment] 2022-05-19 08:52
Did a clean install and turned off every setting within snapmod.But there seems to be something within the mod itself that is causing this issue. I confirmed it twice myself. Will wait for someone else if they are facing the same issue.
Device :Redmi Note 8 pro
Android v: Android 11
MTK Device
Magisk v23

I'll try to find someone else to verify the same too.

**Comment by rodit** [comment] 2022-05-19 11:03
I will add some more debug logging to the auto save feature in a future update so we can get to the bottom of this.

**Comment by Lucky-069** [comment] 2022-05-19 11:08
> ~I will add some more debug logging to the auto save feature in a future update so we can get to the bottom of this.~
> 
> I just read that your last message - if you cannot save _any_ messages then the issue becomes a lot more odd. My best guess is that one of the message filters (which block screenshot notifications for example) is blocking save/unsave notifications as well which would prevent messages from being saved or unsaved. I will completely remove the save/unsave filters in the next update and you can see if that fixes it.

But I even tried turning off every setting in snapmod. Just hooked it with the snapchat and that itself somehow is triggering it.

**Comment by Lucky-069** [comment] 2022-05-19 11:09
So it's not something in the settings that I can toggle to fix its something within the mod or hook. Just guessing Tho!

**Comment by rodit** [comment] 2022-05-19 11:10
@Lucky-069 Hmm - could you upload your shared preferences file? It should be in `/data/data/xyz.rodit.snapmod/shared_prefs/xyz.rodit.snapmod_preferences.xml` (there isn't any sensitive information in there so don't worry).

**Comment by Lucky-069** [comment] 2022-05-19 13:21
> @Lucky-069 Hmm - could you upload your shared preferences file? It should be in `/data/data/xyz.rodit.snapmod/shared_prefs/xyz.rodit.snapmod_preferences.xml` (there isn't any sensitive information in there so don't worry).

Yes I'll do it rn.

**Comment by Lucky-069** [comment] 2022-05-19 13:25
`<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="hide_exit_conversation" value="false" />
    <boolean name="allow_save_snaps" value="true" />
    <boolean name="disable_metrics" value="true" />
    <boolean name="use_android_download_manager" value="true" />
    <boolean name="bypass_video_length_restrictions" value="true" />
    <boolean name="enable_custom_snap_download_path" value="false" />
    <boolean name="hide_read" value="false" />
    <boolean name="allow_download_public_dp" value="true" />
    <string name="preview_messages_count">5</string>
    <string name="audio_playback_speed">1.0</string>
    <boolean name="auto_save_all_chats" value="true" />
    <boolean name="unlimited_snap_duration" value="true" />
    <set name="global_log_level">
        <string>1</string>
        <string>2</string>
        <string>4</string>
    </set>
    <boolean name="hide_enter_conversation" value="false" />
    <string name="download_path_story">$Movies/SnapMod/%u_story_%t</string>
    <boolean name="hide_story_views" value="true" />
    <boolean name="disable_spotlight" value="true" />
    <boolean name="allow_public_profile" value="true" />
    <boolean name="show_toast_on_download" value="true" />
    <string name="friend_override">ADDED_BY_USERNAME</string>
    <boolean name="auto_download_snaps" value="false" />
    <boolean name="hide_save" value="true" />
    <boolean name="hide_save_gallery" value="true" />
    <boolean name="enable_friend_override" value="true" />
    <string name="download_path_profile">$Movies/SnapMod/%u_profile_%t</string>
    <boolean name="hide_typing" value="true" />
    <string name="location_share_long">0</string>
    <set name="auto_save_types">
        <string>NOTE</string>
        <string>CHAT</string>
        <string>STICKER</string>
        <string>EXTERNAL_MEDIA</string>
    </set>
    <boolean name="location_share_override" value="true" />
    <boolean name="save_any" value="true" />
    <boolean name="hide_replay" value="true" />
    <string name="download_path_snap">$Movies/SnapMod/%u_snap_%d</string>
    <string name="update_frequency">0</string>
    <boolean name="log_network_requests" value="false" />
    <boolean name="disable_bitmojis" value="false" />
    <boolean name="disable_snap_splitting" value="true" />
    <boolean name="hide_screenshot" value="true" />
    <string name="override_snap_timer">0</string>
    <boolean name="enable_new_voice_notes" value="true" />
    <string name="download_path_audio_note">$Movies/SnapMod/%id_audio_%t</string>
    <boolean name="allow_pin_chats" value="true" />
    <boolean name="override_snap" value="false" />
    <boolean name="allow_download_stories" value="true" />
    <string name="location_share_lat">0</string>
    <boolean name="dont_release" value="true" />
    <string name="public_dp_resolution">500</string>
    <boolean name="more_profile_info" value="true" />
    <string name="download_date_format">dd-MM-yyyy_HH:mm:ss</string>
    <boolean name="enable_snap_type_override" value="false" />
    <boolean name="block_ads" value="true" />
</map>
`

**Comment by rodit** [comment] 2022-05-19 13:31
Yeah it contains 'hide_save' just change '<boolean name="hide_save" value="true" />' to '<boolean name="hide_save" value="false" />' or wait for the next update (I have removed this option as it doesn't work).

**Comment by Lucky-069** [comment] 2022-05-19 14:16
> Yeah it contains 'hide_save' just change `<boolean name="hide_save" value="true" />` to `<boolean name="hide_save" value="false" />` or wait for the next update (I have removed this option as it doesn't work).
> 
> Alternatively just disable the 'Hide Chat Saves/Unsaves' option in snapmod's settings.

The thing is I can't the option in the app lol
You can check the ss above I sent!

**Comment by Magna-Graecia** [comment] 2022-05-19 14:19
@rodit Wait, the "Hide Chat Saves/Unsaves" option is gone from my SnapMod settings. I assumed you had removed it because it wasn't working for anyone. Is Lucky-069 not on the latest version of SnapMod, or am I missing something here? lol

Just went and verified and it's definitely gone. I actually thought this might have been Lucky-069's issue because I remember when I would have this option enabled, it wouldn't let me save/unsave messages by tapping on them. It was like it was frozen, so I just kept that option disabled. Lucky-069's issue descriptions sounded very similar, so I went and checked to see the name of the option so I could tell him to make sure it was disabled, and then I noticed it was gone.

Just saw Lucky-069's post stating that the option is gone for him as well, so I'm not imagining things lol. Check the screenshots of his settings and you'll see that it's gone. Maybe you forgot that you actually removed it before this most recent update? So maybe you removed the actual setting option in the app but not in the xml.

**Comment by Lucky-069** [comment] 2022-05-19 14:20
@rodit Thanks a ton! I couldn't find the toggle hide chat saves/Unsaves in the mod but I manually edited the value to false and it worked!

**Comment by rodit** [comment] 2022-05-19 14:21
Very odd I thought I hadn't removed it yet - just edit your shared preferences file then as suggested (or just delete it - settings will be reset to default).

**Comment by Lucky-069** [comment] 2022-05-19 14:21
> @rodit Wait, the "Hide Chat Saves/Unsaves" option is gone from my SnapMod settings. I assumed you had removed it because it wasn't working for anyone. Is Lucky-069 not on the latest version of SnapMod, or am I missing something here? lol
> 
> Just went and verified and it's definitely gone. I actually thought this might have been Lucky-069's issue because I remember when I would have this option enabled, it wouldn't let me save/unsave messages by tapping on them. It was like it was frozen, so I just kept that option disabled. Lucky-069's issue descriptions sounded very similar, so I went and checked to see the name of the option so I could tell him to make sure it was disabled, and then I noticed it was gone.
> 
> Just saw Lucky-069's post stating that the option is gone for him as well, so I'm not imagining things lol. Check the screenshots of his settings and you'll see that it's gone. Maybe you forgot that you actually removed it before this most recent update? So maybe you removed the actual setting option in the app but not in the xml.

Exactly and now it works just fine. Autosave works after I edited it. Imagine I spent 2 days on this lololol.

**Closed as completed** 2022-05-19 14:21 UTC
Labels: bug
