### ISSUE TITLE
[Bug] Saved image-snaps become 3 second videos in gallery

### ISSUE THREAD

**Issue by tarek133** [rodit/SnapMod#176] opened 2022-06-02 16:28 UTC
So this issue has been there since the last version, and still is present with 1.8.0. I'm using latest Snapchat as well.
The issue is, when I save normal snaps (literally just an image, with no filters whatsoever) the snap gets saved as a 3 second .mp4 file  in the gallery.
![Screenshot_20220602-182044](https://user-images.githubusercontent.com/12681440/171678059-82431866-b5f3-46e4-a875-d9f2a4167164.png)
Using OnePlus 8 Pro with Android 11 and latest LSposed.

Here's some LSposed logs:
https://onlyfiles.io/f/60e9e68c79024c51a2e2dc9af626b7b6

Weirdly enough, it's only for saving snaps. Saving stories works fine and the image gets saved as jpg still

**Comment by rodit** [comment] 2022-06-02 17:38
This is a duplicate of #143 (it seems to be to do with having long snaps enabled, although I'm not sure).

I do not currently have a fix for this.

**Closed by rodit** 2022-06-02 17:38 UTC
