### ISSUE TITLE
Stealth Mode not fully working

### ISSUE THREAD

**Issue by Magna-Graecia** [rodit/SnapMod#63] opened 2022-04-26 16:03 UTC
Just updated and was able to test it out. Happy to report that stealth snap viewing IS working for me with stealth mode enabled. Unfortunately "hide typing" and "hide bitmoji chat presence" is still not working.

I also tested using the individual "hide read receipts", "hide bitmoji chat presence", and "hide typing" toggles from within SnapMod just to see if they worked now, and they still don't work, but I don't think they were intended to for this update. Just stealth mode. "Hide read receipts" still works for hiding chat reads, but not for hiding snap views. Stealth mode works for both.

@snaphappy1 maybe you can test for yourself and report back with your findings since I know you have the same setup as me

**Comment by rodit** [comment] 2022-04-26 16:23
Thought it might not still work. Read receipts is only for text messages, the separate option 'Hide snap views' is for snap views.

**Comment by Magna-Graecia** [comment] 2022-04-26 16:28
Yep, literally just noticed the new separate option for "hide snap views" and was about to report back on that when your reply popped up haha. The "hide snap views" option also works individually without stealth mode enabled, so that's good news! Unfortunately "hide bitmoji chat presence" and "hide typing" don't work whether using stealth mode or individual options. I'm sure you'll get it figured out soon enough :)

**Comment by Magna-Graecia** [comment] 2022-04-27 15:51
Nope, nothing yet unfortunately :( .. I did make sure to kill Snapchat twice (this was after a full reboot after updating SnapMod). I tried with only stealth mode enabled, only individual options enabled, and also with both stealth mode and individual options enabled. I got nothing for both 'Hide Bitmoji Presence' and 'Hide Typing'.

One thing I want to ask about: I have auto updates disabled for Snapchat so I can choose when to update since they might release one that doesn't work with the latest version of SnapMod. My idea is to update Snapchat whenever SnapMod updates to reflect the latest version. However, there was an update on April 24 from looking at the Play Store, and I did receive notification on my device that the app needed updating, which I ignored since I was already on the latest version of Snapchat that SnapMod supports. This version is 11.75.0.33, which is still the version number listed on the Play Store even though there has been an update since 11.75.0.33 was released (like I said, there was one on the 24th). I also went to the 'manage my apps' section on my device, and it said Snapchat was updated 14 minutes ago at the moment that I checked. I believe it was indicating that Snapchat was somehow updated in the store, not on my device because my device still has an 'Update' option since auto updates are disabled and I haven't updated.

Should I update Snapchat and try again? Just curious if this could be why.

Also, I saw someone just posted an issue regarding snaps being sent as chats instead of live and thought maybe the new update broke something, so I tested that out as well. For informational purposes, I can confirm on my end that it's still working as normal, so I'm not sure what's wrong on their end.

@snaphappy1 Can you possibly test the latest features on your end and report back with your experience? Just so we can rule out that it's not a 'me' problem.

**Comment by rodit** [comment] 2022-04-27 18:59
The update has probably just released (if there is one) - it's not even on APKMirror yet. Bitmoji presence hiding works fine for me so you either have the update or the mappings haven't reloaded (are you sure you installed the latest mappings?). It might be worth clearing Snapmod's data and reinstalling the mappings. Features like chat presence and sending gallery as snaps should work for everyone if they work for me.

**Comment by Magna-Graecia** [comment] 2022-04-28 06:23
Ya, but I don't think the updates between when 11.75.0.33 released and today were new version updates. These were minor intermediary updates. Snapchat sends out a lot of these intermediary updates. As of right now, there's no new version beyond 11.75.0.33 except for the betas, but there has been Snapchat updates since 11.75.0.33 was first released. My device is prompting me right now that Snapchat has an update but needs approval because I have auto-update turned off for it even though I already have 11.75.0.33 (84591) installed. It even tells me right at the top of SnapMod and says that it's supported.

Anyway, I went into /data/data/xyz.rodit.snapmod/files/ to confirm that I had the mappings installed, and I indeed do. I had one for 84588 and one for 84591. I thought maybe the 84588 for the older version might have been being used or otherwise causing conflict, so I did as you suggested and cleared SnapMod's data. Before reopening it, I went back to /data/data/xyz.rodit.snapmod/files/ to confirm that they were gone, and they were. It was empty. I then opened SnapMod and was prompted to download. I downloaded, and then went back to /data/data/xyz.rodit.snapmod/files/ and confirmed that only 84591 was there. I then set all of my SnapMod settings, started Snapchat, force killed it, started it again, force killed it again, and started one last time before checking if "Hide Typing" and "Hide Bitmjoji Presence" were working. They weren't. I once again tested with only stealth mode enabled, only individual options enabled, and with both enabled, all while closing and reopening Snapchat in between changes. I got nothing.

I know it works for you, but I believe you're on a different version of Android and also using LSPosed, right? There must be something with Android 8.1.0 or original Xposed, especially since snaphappy1 was experiencing the exact same issues with the same setup. This is why I really hope we can hear back from him on how the latest version is working for him. Does tagging on here give a notification to the user? @snaphappy1 if you get this notification, can you confirm if "Hide Typing" and "Hide Bitmoji Presence" is working for you with the lastest SnapMod?

Also, sending gallery as snaps does work for me. I was saying that another user opened an issue after the most recent update stating that it wasn't working. I was only confirming that it was indeed working on my end, so it wasn't an issue with the update. It was something local to him.

**Comment by snaphappy1** [comment] 2022-04-28 12:01
My findings are the same as Magna-Graecia with a fresh install of SnapMod 1.5.2 and Sc 11.75 latest from Playstore. I've confirmed with multiple people my bitmoji still shows. Everything else works perfectly tho. The new per convo stealth option right from inside sc is amazing! Thank you so much!

**Comment by snaphappy1** [comment] 2022-04-28 12:06
Also I've intalled SnapMod on a device running Android 11 with Riru/Lsposed. SnapMod on Lsposed runs exactly the same as on orignal xposed. Everything works except Bitmoji showing in chat. This is the setup:

![Screenshot_20220428-074313_Shell](https://user-images.githubusercontent.com/104136656/165748071-66d6b96d-5d76-4f33-82e7-4be6d33b5386.png)

![Screenshot_20220428-074345_Shell](https://user-images.githubusercontent.com/104136656/165748108-411b2073-1cb4-4de3-89f8-c247bfef4c07.png)

![Screenshot_20220428-075124_SnapMod](https://user-images.githubusercontent.com/104136656/165748377-47b3e5e7-ce58-4d25-9519-e9cf29b4026c.png)

**Comment by rodit** [comment] 2022-04-28 14:20
This is very odd. Could you check the LSposed/XPosed logs for me and see if there are any errors. Open Snapchat and enter a conversation and then check the logs. I only have Android 10+ devices to test with (and don't really have time to setup an emulator with magisk/xposed etc) so there isn't a lot I can do unfortunately.

**Comment by rodit** [comment] 2022-04-28 14:20
Another thing could be what devices other people are using - the people that can see your bitmoji, are they on Android or iOS?

**Comment by Magna-Graecia** [comment] 2022-04-28 22:21
@snaphappy1 Thanks a lot for getting back with your findings! They are as I thought they would be. Just to confirm, are both "Hide Bitmoji Presence" AND "Hide Typing" still not working for you? You commented only that "Bitmoji Presence" wasn't working, but what about "Hide Typing"? Both still don't work for me.

@rodit I'm testing all features myself using 2 Android devices and 2 Snapchat accounts. The other device is not rooted or modded in any way and is running the latest Snapchat. I think it would basically break the purpose of the app if things only worked depending on what device the user you were using any stealth against had. It would be unreliable at that point because you don't always know what device, OS version, Snapchat version, etc they're using. And even if you did, you would need to keep mental tabs on who you can be stealthy with, and who you can't lol. It has to work across the board, otherwise it starts to become meaningless. I didn't know that Xposed logs could help you, otherwise I would definitely have been sending them for you. I attached one for you to look at, but looking at it myself it looks like it's not very fruitful. It seems like it's just hooking Snapchat and loading the cached mappings for 84591. No errors. I tested it out by both entering a conversation, as well as typing a message.
[error.log](https://github.com/rodit/SnapMod/files/8587013/error.log)

**Comment by snaphappy1** [comment] 2022-04-29 01:12
While using an Android 11 device with Riru/Lsposed I tested using my other phone running Android 8.1 systemless xposed and confirmed with friends running unmodded Android 10 (LG G7 ThinQ) and Android 12 (Samsung Galaxy S10e and Samsung Galaxy Z Flip3 5G)


I had hide bitmoji presense enabled as well as hide typing notifications. I tried hide read receipts and stealth mode as well. They could still see my bitmoji in the chat. I even tried deleting my bitmoji from sc, still they could see that little dot/smiley face lol.

[modules_2022-04-28T18_30_15.518.log](https://github.com/rodit/SnapMod/files/8587536/modules_2022-04-28T18_30_15.518.log)

[verbose_2022-04-28T18_30_15.512.log](https://github.com/rodit/SnapMod/files/8587537/verbose_2022-04-28T18_30_15.512.log)

**Comment by Magna-Graecia** [comment] 2022-04-29 09:38
@snaphappy1 Good stuff, man. You've helped confirm that it's not just a "me" problem for neither you or myself. Hopefully rodit can extract some useful information out of the logs and figure out what's going on. Fingers crossed

**Comment by rodit** [comment] 2022-04-29 14:17
There are no errors in those logs so I cannot possibly think of why it would work for me. I am testing with two Android 10 devices (one completely untouched, just with Snapchat installed, the other with Magisk and LSPosed with Snapmod). Maybe it will miraculously fix itself in the next update, otherwise I have no idea what the cause is.

**Comment by jammyjay** [comment] 2022-04-29 17:20
Have you tried using Zygisk with LSPosed instead of Riru

**Comment by Magna-Graecia** [comment] 2022-04-29 17:43
> There are no errors in those logs so I cannot possibly think of why it would work only for me. I am testing with two Android 10 devices (one completely untouched, just with Snapchat installed, the other with Magisk and LSPosed with Snapmod). Maybe it will miraculously fix itself in the next update, otherwise I have no idea what the cause is.

I doubt it if I'm being completely honest

**Comment by jammyjay** [comment] 2022-04-29 22:53
> > Have you tried using Zygisk with LSPosed instead of Riru
> 
> Is everything working for you?

Yes it is. Just tested it out just now.

**Comment by snaphappy1** [comment] 2022-04-30 05:35
I tried Zygisk/Lsposed with same results as riru. Bitmoji still shows, no errors in Lsposed. Even tried the latest sc update 11.76 but the mappings were incompatible, renaming with build number made no difference. Since it's working for two people now, dev rodit and jammyjay, it must be on our end. Perhaps our devices are too old? The latest OS for my phone was Pie/9, but I installed Android 11 thru LinegeOS, so it's not truly official. Also my devices are armeabi-v7a, whereas newer phones have arm64-v8a. That could be it. Either way, everything else works on the mod, so I am more than happy with how it is now. Thank you dev rodit!


![Screenshot_20220430-012509_Shell](https://user-images.githubusercontent.com/104136656/166092796-cd48db55-f1dd-42e8-b981-457f3996f4f9.png)

![Screenshot_20220430-012559_Updater](https://user-images.githubusercontent.com/104136656/166092807-7abe2072-241a-40aa-900e-ac315a4a346a.png)

**Comment by rodit** [comment] 2022-04-30 15:00
@Magna-Graecia are you also on a 32bit device?

**Comment by Magna-Graecia** [comment] 2022-04-30 17:44
@jammyjay Thank you!

@snaphappy1 Yes indeed, this could be it. I agree, the app is amazing as it is, but I really wish we could get at least "hide bitmoji presence" working. It's sort of needed if you're using "hide read receipts" and don't wanna get busted reading the message haha. Right now the app is like 80% for me. With "hide bitmoji presence" it would be 100% as-is. I don't even need "hide typing" or "hide replay notifications".

@rodit According to this: https://www.devicespecifications.com/en/model/b1d63c81 my device is ARMv8-A. However, I installed 2 separate hardware checkers (Inware and Droid Hardware Info), and Droid Hardware Info states: "Instruction Sets: armeabi-v7a, armeabi", while Inware states: "Supported ABIS: armeabi-v7a, armeabi". Both correctly state the SoC as a Samsung Exynos 7870, which uses the ARM Cortex-A53 CPU, which according to this: https://en.wikipedia.org/wiki/ARM_Cortex-A53 implements the ARMlv8-A 64-bit instruction set. devicespecifications.com also states the CPU bits as 64-bit.

So I guess it's a 32-bit device with a 64-bit instruction set? Found this XDA thread with a couple senior members replying stating that it's ARM (32-bit): https://forum.xda-developers.com/t/t580-installing-xposed.3554703/

**Comment by snaphappy1** [comment] 2022-04-30 19:25
Try the 64bit version of sc from apk mirror, if it doesn't fail on install, then your device is 64bit and my theory is incorrect. In the meantime, you could also do the classic right swipe from their bitmoji, that allows you to see the chat while hiding your bitmoji, but if you swipe too far it will expose you lol.

**Comment by Magna-Graecia** [comment] 2022-04-30 20:59
@snaphappy1 Nope, didn't work, so I'm pretty sure it's indeed 32-bit with 64-bit instructions or something. You can see the OP in the XDA thread I linked was also confused on that because the ARM Cortex A-53 is 64-bit. 

Anyway, they didn't have 11.76.1.34 up on APKMirror yet, so I downloaded and installed the 64-bit version of 11.75.0.33 just to test. It said "App not installed" right at the end of the install process haha. This doesn't mean that 32-bit architecture is indeed the root of the problems we're facing, but it sure does lend to that theory! It would be nice if we had more people with 32-bit devices willing to test.

By classic right swipe do you mean partially opening the chat? That's ghetto. I'm posh and need a full-fledged feature! 😂😂😝

**Comment by Magna-Graecia** [comment] 2022-04-30 21:12
@snaphappy1 Actually you know what? I just did a quick search and learned that it's not just hardware that's related to architecture, it's the OS too. So even if my hardware was capable of 64-bit, as has been alluded to with the ARM Cortex A-53, I would need to be on a 64-bit version of Android. I can install a 64-bit version of Android as long as my hardware is capable of it (if we are to assume that the ARM Cortex A-53 indeed is as stated in the technical documentation), but do I really wanna go that far just to test and see if SnapMod finally works? I think not 😂

So 64-bit Snapchat may not have installed due to having a 32-bit OS, and not because of the hardware.

**Comment by No-WaY-SA** [comment] 2022-05-01 00:49
Sorry,  where to find stealth mode? And dose snapmod need root permissions? Or only lsposed activation to work in accurate manner?

**Comment by Magna-Graecia** [comment] 2022-05-01 00:57
> Sorry, where to find stealth mode? And dose snapmod need root permissions? Or only lsposed activation to work in accurate manner?

It doesn't need superuser granted, just activated in LSPosed manager. Stealth Mode can be found by long pressing on a chat until the context menu pops up. It's a toggle switch at the bottom of that menu.

**Comment by No-WaY-SA** [comment] 2022-05-01 01:03
Thanks alot for help , so stealth mode cannot be universal option? Only per chat?

**Comment by snaphappy1** [comment] 2022-05-01 12:34
@Magna-Graecia we have a lot in common. My device which runs systemless xposed is also 64bit capable but runs a 32bit OS lol. Apparently from around 2015 to 2020, devices that had less than 4gigs of ram were sometimes installed with 32bit OS's as they were deemed more stable. My device is from 2018 


![Screenshot_2022-04-30-19-15-17](https://user-images.githubusercontent.com/104136656/166145722-b81a8c40-a040-464c-9993-2acb966707e3.png)


Anyways I don't want this thread to get off topic. We need solutions. Any of these 3 things could help us out....

1) if someone with an arm64-v8a capable/enabled device can install the armabi-v7a version of sc from apk mirror then test if that breaks hiding bitmoji in chat. That would confirm everything.

2) if dev rodit could take time from his busy life and temporarily install armeabi-v7a sc then create a mapping file for us to test just once? I feel like we've asked a lot already. 

3) We take computer science courses to learn how to use rodit's dexsearch to create mapping files on our own.. lol

For me, hiding bitmoji presence is not a priority since the ghetto swipe trick works well enough to get by lol.

**Comment by rodit** [comment] 2022-05-01 12:40
I will try the v7a apk later today. I have little hope that it'll be different on my device - the Java code (which is what gets hooked by Xposed) is the same for all abi versions of Snapchat (they only differ in their native libraries). My best guess is that, if it is a 32 vs 64 bit problem, there is some code in the Java code that detects platform ABI and then changes how it handles Bitmoji presence based on ABI. I have no idea why the same method would not be used by Snapchat on every ABI but it's worth testing.

**Comment by rodit** [comment] 2022-05-01 13:36
As expected, it still works for me with the v7a apk installed.

**Comment by Magna-Graecia** [comment] 2022-05-02 00:20
@snaphappy1 Oh Device Info HW! I saw this one on the list of recommended device info checkers that I researched. I didn't know that it actually detailed both the current mode and supported mode. I just installed it and got the same results as you. 32-bit current, 64-bit supported, so it looks like my suspicions were correct, and so yes indeed we do have a lot in common haha. My device is from 2016 and has 2 GB RAM, so that makes sense. I wonder if the fact that we both have an ARM Cortex A-53 has anything to do with it.

Solution 3 sounds the most reasonable. I am now putting all other life goals on hold just to get Hide Bitmoji Presence fixed once and for all. It is written, so it shall be done. SnapMod is love, SnapMod is life 😂

Also, I'm now officially coining the term as "ghetto swiping." "Just ghetto swipe it, bro."

Since you like playing around with and installing custom ROMs, you should try installing a 64-bit version of Android if it interests you, and seeing if it works from there, but that's all up to you of course. I personally am on my stock ROM with no interest in changing yet. I don't think installing 32-bit Snapchat onto a 64-bit device/OS is going to say much, which rodit has now demonstrated to be true. I think running 32-bit or 64-bit Snapchat on a device that's 64-bit capable and previously had a 32-bit OS, but now has a 64-bit OS would be a lot more telling. Rodit's test has confirmed that at least it's not the version of Snapchat that matters, so it's likely the device/OS that does.

@rodit So what do you think based on these findings? You think there's any way to make it work for us 32-bit OS scrubs now that you have some pretty clear indication on what it likely is? 😂. Or maybe have 2 versions of the app?

**Comment by rodit** [comment] 2022-05-02 13:57
I couldn't find any other code that could possibly handle Bitmoji presence so, for now, there isn't much I can do to fix this.

**Comment by Magna-Graecia** [comment] 2022-05-02 20:12
> I couldn't find any other code that could possibly handle Bitmoji presence so, for now, there isn't much I can do to fix this.

Ah well, that's unfortunate :(. But I understand. Thanks anyway for what you've created :)

**Comment by seeknay** [comment] 2022-05-04 18:48
Thank you for SnapMod. I have tried two different phones running Android 10 and Hide Bitmoji Presence does not work on either phone.
Would it be possible to add storing messages locally so they could be read in SnapMod like with SnapTools? That could be a way to read messages without the sender knowing. Thanks again.

**Comment by rodit** [comment] 2022-05-04 18:54
@Magna-Graecia I didn't change anything so I have no idea why it would start working.

@seeknay what version of Snapchat and SnapMod are you using? That isn't a really a feature I planned on implementing although I might change my mind.

**Comment by seeknay** [comment] 2022-05-04 19:08
@rodit After reading Magna-Graecia's comment about it working on the latest versions, I upgraded to Snapchat 11.77.0.27 and SnapMod 1.5.5 to try "Hide Typing" and "Hide Bitmoji Presence" again but they did not work.

**Comment by Magna-Graecia** [comment] 2022-05-04 23:34
@rodit Crazy! It's hilarious that you said "maybe it will miraculously start working on the next update" and then boom, it does start working on the next update lmao. I just checked again right now and it's definitely working when enabled. Bitmoji and typing shows when not enabled as expected, so it's definitely not a fluke where both Snapchat features just became broken locally for me after updating Snapchat. It's actually the SnapMod features working as intended. I want to see what snaphappy says when he gets notification of my ping and checks it out.

It's also kind of hilarious that it previously wasn't working for snaphappy and I while on Android 8.1, but it was working for you and others on Android 10. Now it's working for me on Android 8.1, and someone just commented that it's not working for them on Android 10 lol. I assume it's still working for you though, correct?

By the way, what is the version.json for in assets? I assumed all someone would need when downloading and installing an older version would be the apk and bindings.json.

@seeknay There could be a number of issues going on with your situation. Do you have a root browser and have confirmed that you have the 84602.json file in /data/data/xyz.rodit.snapmod/files/ or /Android/data/xyz.rodit.snapmod/files/ ? What device are you using? Can you say if it's 32-bit or 64-bit, and the mode it's currently in?

Give rodit your device info, Xposed version (original Xposed, LSPosed, etc), and try enabling "Hide Bitmoji Presence", going into a chat, and then immediately checking the Xposed/LSPosed log for errors. Preferably save the log and upload it here for rodit. This is your best bet for potentially giving him an idea of what might be happening.

**Comment by snaphappy1** [comment] 2022-05-05 10:50
After reading the good news from Magna-Graecia, I immediately updated sc and snapmod to the newest versions and instantly tested... Unfortunately it is not working for me. Tried on systemless xposed and Lsposed, nothing. Bitmoji still shows. Then I tried something different. I created a new sc account and... Viola. Stealth bitmoji chat hiding works. Even tried with previous versions of sc and snapmod, still works. It's been working this whole time, but only with newer sc accounts. I did try to delete cache and storage and log in again on my old accounts to update the sc token. But no dice. It seems sc might be using different technology, perhaps websockets on old accounts and server events in new accounts? Idk, but if someone absolutely needs their bitmoji in chat hidden, I suggest they make a new account or wait for their old account to miraculously start working lol. I did notice another thing. With the new account I created, the chat arrow is on the left side and stealth fully works, whereas my all my old sc accounts all have the arrow on the right side and bitmoji chat hiding is broken on all of them.  Same phones, same snapmod and sc versions, arrows on different sides 🤷🏻‍♂️



![Screenshot_20220505-062447_Snapchat](https://user-images.githubusercontent.com/104136656/166908084-21f4b2ce-bee4-4cf9-bf0a-e1fcd4861394.png)

------
------
------

![Screenshot_2022-05-05-03-25-38](https://user-images.githubusercontent.com/104136656/166908111-a0fd9385-e0c2-43ef-8d07-1d148d0cfdca.png)

**Comment by rodit** [comment] 2022-05-05 14:24
It could be that Snapchat does AB testing on a per-account basis and all new accounts are placed in the new testing group (which makes Bitomoji hiding work). However, the arrow is on the right for me (on the sending and receiving end) and hiding works. I'll have a look at the experiments part of the app to see if there's anything related to presence at some point.

**Comment by Magna-Graecia** [comment] 2022-05-06 04:18
@snaphappy1 Well color me shocked. I was SURE it would work for you now. That's absolutely INSANE the way it is working though (on new accounts you create, but not old accounts), but should I really be surprised? I mean we have tarek133 over here who has snaps/stories not saving when he has his phone on the charge, but working perfectly fine when it's unplugged. I mean wtf? So who knows what to think with Snapchat anymore. We probably have a SC dev reading this repository and changing random things on random devices at this point just to mess with us 😂😂. For the record, I have the arrow on the right side on both sending and receiving ends the same as rodit, and the account I'm using to send is an old account. I can't say whether or not the arrow changed positions after updating though. I didn't pay enough attention to notice previously.

Try deleting Snapchat data on your device, then logging in with your old account on a different device after having deleted Snapchat data on that one as well (preferably a stock non-rooted/non-modded device). Then delete the data on that device, and go log back in with the old account on your main device. The reason I say to do this is because I regularly do this when wanting to change accounts between my devices. I never actually logout. I just delete data on the devices when logging out/in. I had done this in between this most recent SnapMod/Snapchat update and the last one, and maybe it fixed it but I never noticed because I didn't check until this most recent update, and so I automatically assumed it was because of the update when it maybe wasn't. It doesn't hurt to try, especially with how goofy things seem to work with Snapchat. Maybe it "resets" the token or something.

@rodit I think using one of snaphappy1's old accounts that has it broken would tell you straight away if it's purely account related. If it doesn't work for him on his device, but works for you on yours, then you know it's not. If it doesn't work on either, but your accounts work fine on your devices, then we know it has to be account related or maybe a combination of account AND device. Testing that is up to you though of course.

Also, I had asked previously, but could you tell me what version.json listed in the assets section of releases is for? Is it required for someone who was installing an older version of SnapMod? Or is only the apk and bindings.json required? Thank you ☺️

**Comment by snaphappy1** [comment] 2022-05-06 09:29
Seems the account I was going to donate to rodit magically started working. So did two others. I didn't even re-login to any of them, they just hide bitmoji now. I guess sc is working on things behind the scenes. Would have been nice to figure out why some accounts worked and others didn't just so we could be sure they wont magically stop working again. Either way this is excellent news

**Comment by Magna-Graecia** [comment] 2022-05-06 12:36
@snaphappy1 The Snapchat dev trolling this repository saw your recent comment and was like "now I'm gonna mess with this guy by making the accounts suddenly work just for the memes hahahaha". That's my theory, and I'm sticking with it! Jk 😂😂

No but seriously, that's insane. It's definitely account related then. I mean nothing has changed with your device or Snapchat/SnapMod from a software standpoint, so it has to be account related at the server level. "Next, on Unsolved Mysteries. In the quiet town of Anywheresville, a man by the name of snaphappy1 is trying hard to hack his Snapchat, but did this smartphone user end up getting more than he bargained for when his phone keeps throwing him fastballs and driving him crazy? FIND OUT NEXT when we return after a brief message from our sponsors."

Well it's working now, so that's what matters. The only thing I've found kind of annoying is that when enabling Stealth Mode now when there's an unread message from someone, and then going into the chat to read it, the chat constantly slingshots to the bottom if I try to scroll up and read previous messages and lift my finger off the screen. It's not a big deal, but sometimes I read messages a whole lot later, so I check them in stealth and scroll up to see the previous messages for context, or even to read part of the message that's above if it's a long one, and if I lift my finger it slingshots back to the bottom. It only happens when Stealth Mode is enabled and there's an unread received chat. It doesn't do it in chats with no unread messages, or with sent chats. Are you experiencing this as well? I don't remember it doing this prior to 1.5.4

Maybe it's an intended feature by rodit. The benefit of it is that it reminds you that Stealth Mode is enabled for that chat when you see it slingshotting to the bottom, and that you probably shouldn't type a message and send it without going and disabling Stealth Mode first if you don't want the receiver to go "huh? wtf? How did they reply to me without even having read the initial message?" lol. It does work for that, but at the same time it's annoying when needing to scroll up in the chat.

**Comment by rodit** [comment] 2022-05-06 15:39
The version.json contains the latest version code and supported Snapchat build so SnapMod can tell whether it needs an APK update or just a mappings update (if the version code in version.json is greater than the version code installed on the device checking for updates, then an APK update is required).

The slingshotting is not intended haha. Again, in regards to users experiencing different things working and not working, I can almost guarantee it is features/code refactors being rolled out to only certain users. I don't think it's at all mysterious.

**Comment by Magna-Graecia** [comment] 2022-05-07 09:29
@rodit Thank you! So do we need to download the version.json file and place it somewhere when downloading an older version of SnapMod? Or do we only download the apk and bindings.json and place bindings.json in /data/data/xyz.rodit.snapmod/files/ (while renaming 'bindings' to the version code of Snapchat that the mappings correspond to)? I'm asking in case a newer version of SnapMod ever breaks things and I need to fall back on an older version that worked.

Haha makes sense, but you gotta admit the slingshotting does work to remind you that Stealth Mode is currently enabled, so you can see why I thought that 😂. So does this mean that we should expect some currently working features to go back to being broken once our accounts are pulled out of AB testing? Or is it the other way around where users that currently have some features not working should expect them to become working in the near future?

**Comment by rodit** [comment] 2022-05-07 14:03
@Magna-Graecia No, you only need the bindings.json (renamed to the correct version code like you say) and the APK. You can also place the bindings json in the external data folder as well (Internal Storage/Android/data/xyz.rodit.snapmod/files).

I would assume if you're put in a testing group for new features, you stay in that group until the change is rolled out globally. Things shouldn't start breaking after they start working.

**Comment by Magna-Graecia** [comment] 2022-05-07 15:45
@rodit Great! Thank you for informing me ☺️

Awesome! I'm glad to hear this. The way it was spoken about had me worried that it might only be temporary while we were in AB testing or something haha

**Comment by rodit** [comment] 2022-05-11 12:38
I am closing this issue as I expect, eventually, this will just start working for everybody and I do not see a way to fix it for those who it doesn't work for.

**Closed by rodit** 2022-05-11 12:38 UTC
Labels: bug, wontfix

**Comment by Magna-Graecia** [comment] 2022-05-11 15:29
Sounds good!
